[I 241105 12:43:26 command:168] Visit me at http://0.0.0.0:5555
[I 241105 12:43:26 command:176] Broker: redis://localhost:6379/0
[I 241105 12:43:26 command:177] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'celery_worker.task.process_task',
     'celery_worker.task.run_user_automation',
     'celery_worker.task.schedule_next_day']
Traceback (most recent call last):
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/bin/celery", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ~~~~~^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/flower/command.py", line 57, in flower
    flower_app.start()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/flower/app.py", line 72, in start
    self.listen(self.options.port, address=self.options.address,
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                ssl_options=self.ssl_options,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                xheaders=self.options.xheaders)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/tornado/web.py", line 2211, in listen
    server.listen(
    ~~~~~~~~~~~~~^
        port,
        ^^^^^
    ...<4 lines>...
        reuse_port=reuse_port,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
        port,
    ...<4 lines>...
        reuse_port=reuse_port,
    )
  File "/Users/bibektimilsina/Library/Caches/pypoetry/virtualenvs/backend-yJOuBi-v-py3.13/lib/python3.13/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
    ~~~~~~~~~^^^^^^^^^^
OSError: [Errno 48] Address already in use
